apiVersion: v1
kind: ConfigMap
metadata:
  name: << index .CustomTemplateValues  "example-cm" >>
  namespace: << index .CustomTemplateValues "namespace" >>
  annotations:
    source_repo: <GITOPS_REPO_URL>
data:
  <<- range $key, $val := $.CustomTemplateValues.exampleCmData >>
  << $key >>: << $key >>
  <<- end >>
