apiVersion: v1
kind: ConfigMap
metadata:
  name: ${k1 index .CustomTemplateValues  "example-cm" }
  namespace: ${k1 index .CustomTemplateValues "namespace" }
  annotations:
    source_repo: <GITOPS_REPO_URL>
data:
  ${k1- range $key, $val := $.CustomTemplateValues.exampleCmData }
  ${k1 $key }: ${k1 $val }
  ${k1- end }
